2013-02-08 09:48:13,109 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.ParentRunner$run.call(Unknown Source)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure4.call(_GrailsTest_groovy)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
2013-02-08 09:48:13,187 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 09:48:13,250 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 09:48:13,265 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
2013-02-08 09:48:13,265 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
2013-02-08 09:48:13,296 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
2013-02-08 09:48:13,296 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
2013-02-08 09:48:13,453 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantPortuguese(UserControllerFunctionalTests.groovy:35)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.ParentRunner$run.call(Unknown Source)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure4.call(_GrailsTest_groovy)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
2013-02-08 09:48:13,484 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantPortuguese(UserControllerFunctionalTests.groovy:35)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 09:48:13,484 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantPortuguese(UserControllerFunctionalTests.groovy:35)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 09:48:13,484 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantPortuguese(UserControllerFunctionalTests.groovy:35)
2013-02-08 09:48:13,484 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantPortuguese(UserControllerFunctionalTests.groovy:35)
2013-02-08 09:48:13,484 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantPortuguese(UserControllerFunctionalTests.groovy:35)
2013-02-08 09:48:13,484 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [Esta companhia (TheBadTenant) nao existe. Favor usar uma companhia existente para criar este usuario.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantPortuguese(UserControllerFunctionalTests.groovy:35)
2013-02-08 09:48:13,546 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Expected content to loosely contain [SUCCESS] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantSuccessEnglish(UserControllerFunctionalTests.groovy:45)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.ParentRunner$run.call(Unknown Source)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure4.call(_GrailsTest_groovy)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
2013-02-08 09:48:13,562 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [SUCCESS] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [SUCCESS] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantSuccessEnglish(UserControllerFunctionalTests.groovy:45)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 09:48:13,562 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [SUCCESS] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [SUCCESS] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantSuccessEnglish(UserControllerFunctionalTests.groovy:45)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 09:48:13,578 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [SUCCESS] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantSuccessEnglish(UserControllerFunctionalTests.groovy:45)
2013-02-08 09:48:13,578 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [SUCCESS] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantSuccessEnglish(UserControllerFunctionalTests.groovy:45)
2013-02-08 09:48:13,578 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [SUCCESS] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantSuccessEnglish(UserControllerFunctionalTests.groovy:45)
2013-02-08 09:48:13,578 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [SUCCESS] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantSuccessEnglish(UserControllerFunctionalTests.groovy:45)
2013-02-08 10:03:31,562 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:26)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.ParentRunner$run.call(Unknown Source)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure4.call(_GrailsTest_groovy)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
2013-02-08 10:03:31,593 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:26)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 10:03:31,609 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:26)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 10:03:31,625 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:26)
2013-02-08 10:03:31,625 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:26)
2013-02-08 10:03:31,625 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:26)
2013-02-08 10:03:31,625 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:26)
2013-02-08 10:05:15,171 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.ParentRunner$run.call(Unknown Source)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure4.call(_GrailsTest_groovy)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
2013-02-08 10:05:15,203 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 10:05:15,218 [main] ERROR StackTrace  - Full Stack Trace:
URL Stack that resulted in junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
---------------
POST user/createUserInExistingTenant Browser content change
---------------
junit.framework.AssertionFailedError: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.grailsrocks.functionaltest.TestCaseBase.assertContentContains(TestCaseBase.groovy:298)
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:179)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:290)
	at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:248)
	at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:195)
	at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:184)
	at TestApp$_run_closure1.doCall(TestApp.groovy:82)
2013-02-08 10:05:15,218 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
2013-02-08 10:05:15,218 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
2013-02-08 10:05:15,234 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
2013-02-08 10:05:15,234 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: com.grailsrocks.functionaltest.FunctionalTestException: Expected content to loosely contain [This tenant (TheBadTenant) does not exist. Please use an existing tenant to create this user.] but it didn't
	at com.grailsrocks.functionaltest.TestCaseBase.invokeMethod(TestCaseBase.groovy:184)
	at com.moovt.UserControllerFunctionalTests.testCreateUserInExistingTenantBadTenantEnglish(UserControllerFunctionalTests.groovy:24)
